import type { Product, Category } from "@/types/product";

export const WILAYAS: string[] = [
  "Adrar (01)", "Chlef (02)", "Laghouat (03)", "Oum El Bouaghi (04)",
  "Batna (05)", "Béjaïa (06)", "Biskra (07)", "Béchar (08)",
  "Blida (09)", "Bouira (10)", "Tamanrasset (11)", "Tébessa (12)",
  "Tlemcen (13)", "Tiaret (14)", "Tizi Ouzou (15)", "Alger (16)",
  "Djelfa (17)", "Jijel (18)", "Sétif (19)", "Saïda (20)",
  "Skikda (21)", "Sidi Bel Abbès (22)", "Annaba (23)", "Guelma (24)",
  "Constantine (25)", "Médéa (26)", "Mostaganem (27)", "M'Sila (28)",
  "Mascara (29)", "Ouargla (30)", "Oran (31)", "El Bayadh (32)",
  "Illizi (33)", "Bordj Bou Arréridj (34)", "Boumerdès (35)",
  "El Tarf (36)", "Tindouf (37)", "Tissemsilt (38)", "El Oued (39)",
  "Khenchela (40)", "Souk Ahras (41)", "Tipaza (42)", "Mila (43)",
  "Aïn Defla (44)", "Naâma (45)", "Aïn Témouchent (46)",
  "Ghardaïa (47)", "Relizane (48)", "El M'Ghair (49)",
  "El Meniaa (50)", "Ouled Djellal (51)", "Bordj Badji Mokhtar (52)",
  "Béni Abbès (53)", "Timimoun (54)", "Touggourt (55)",
  "Djanet (56)", "In Salah (57)", "In Guezzam (58)",
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Satin Midi Skirt Set",
    slug: "satin-midi-skirt-set",
    category: "women",
    price: 3490,
    images: [
      "/products/Gemini_Generated_Image_3q6hc63q6hc63q6h.png",
      "/products/Gemini_Generated_Image_440k5l440k5l440k.png",
      "/products/Gemini_Generated_Image_4xiapv4xiapv4xia.png",
      "/products/Gemini_Generated_Image_8yapny8yapny8yap.png",
    ],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Sand", hex: "#c8b89a" },
      { name: "Cream", hex: "#f0e6d3" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    badge: "new",
    description:
      "A beautifully crafted satin skirt set in a warm camel tone. Features a flattering A-line silhouette and smooth, lightweight fabric.",
    details:
      "Fabric: 95% Polyester Satin, 5% Elastane · Lining: 100% Polyester · Length: Midi · Closure: Invisible back zip · Machine wash cold, gentle cycle · Made in Algeria",
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
    ref: "LZL-0041",
  },
  {
    id: "2",
    name: "Satin Midi Dress",
    slug: "satin-midi-dress",
    category: "women",
    price: 2390,
    salePrice: 2990,
    images: [
      "/products/Gemini_Generated_Image_9ameg29ameg29ame.png",
      "/products/Gemini_Generated_Image_agy78sagy78sagy7.png",
      "/products/Gemini_Generated_Image_ebfh0webfh0webfh.png",
      "/products/Gemini_Generated_Image_fp4pikfp4pikfp4p.png",
    ],
    colors: [
      { name: "Camel", hex: "#c8a060" },
      { name: "Charcoal", hex: "#3a3a3a" },
      { name: "Ruby", hex: "#b22222" },
      { name: "Cream", hex: "#f0e6d3" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    badge: "sale",
    description:
      "A beautifully crafted satin midi dress in a warm camel tone. Features a flattering A-line silhouette, gathered waist detail, and a smooth, lightweight fabric that drapes elegantly with movement.",
    details:
      "Fabric: 95% Polyester Satin, 5% Elastane · Lining: 100% Polyester · Length: Midi (knee to calf) · Closure: Invisible back zip · Machine wash cold, gentle cycle · Made in Algeria",
    inStock: true,
    rating: 4.9,
    reviewCount: 89,
    ref: "LZL-0042",
  },
  {
    id: "3",
    name: "Modest Camel Coat",
    slug: "modest-camel-coat",
    category: "women",
    price: 5990,
    images: [
      "/products/Gemini_Generated_Image_omcyhvomcyhvomcy.png",
      "/products/Gemini_Generated_Image_ta4kahta4kahta4k.png",
      "/products/Gemini_Generated_Image_x66q0vx66q0vx66q.png",
      "/products/Gemini_Generated_Image_3q6hc63q6hc63q6h.png",
    ],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Camel", hex: "#c8a060" },
      { name: "Cream", hex: "#f0e6d3" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    badge: "new",
    description:
      "A luxurious full-length camel coat with classic lapels. Perfect for layering during the cooler months.",
    details:
      "Fabric: 80% Wool, 20% Polyester · Lining: 100% Viscose · Length: Full · Closure: Button front · Dry clean only · Made in Algeria",
    inStock: true,
    rating: 4.7,
    reviewCount: 56,
    ref: "LZL-0043",
  },
  {
    id: "4",
    name: "Classic Oxford Shirt",
    slug: "classic-oxford-shirt",
    category: "men",
    price: 2490,
    images: [
      "/products/Gemini_Generated_Image_440k5l440k5l440k.png",
      "/products/Gemini_Generated_Image_3q6hc63q6hc63q6h.png",
      "/products/Gemini_Generated_Image_ebfh0webfh0webfh.png",
      "/products/Gemini_Generated_Image_fp4pikfp4pikfp4p.png",
    ],
    colors: [
      { name: "White", hex: "#ffffff" },
      { name: "Light Blue", hex: "#a0c4e8" },
      { name: "Navy", hex: "#1a2744" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    badge: "bestseller",
    description: "A timeless oxford shirt crafted from premium cotton.",
    details:
      "Fabric: 100% Cotton Oxford · Collar: Button-down · Fit: Regular · Machine wash cold · Made in Algeria",
    inStock: true,
    rating: 4.6,
    reviewCount: 203,
    ref: "LZL-0044",
  },
  {
    id: "5",
    name: "Kids Cotton Hoodie",
    slug: "kids-cotton-hoodie",
    category: "kids",
    price: 1790,
    images: [
      "/products/Gemini_Generated_Image_4xiapv4xiapv4xia.png",
      "/products/Gemini_Generated_Image_8yapny8yapny8yap.png",
      "/products/Gemini_Generated_Image_9ameg29ameg29ame.png",
      "/products/Gemini_Generated_Image_agy78sagy78sagy7.png",
    ],
    colors: [
      { name: "Sage", hex: "#8fbc8f" },
      { name: "Sand", hex: "#c8b89a" },
      { name: "Navy", hex: "#1a2744" },
    ],
    sizes: ["4Y", "6Y", "8Y", "10Y", "12Y"],
    description:
      "A soft cotton hoodie perfect for active kids. Comfortable and durable.",
    details:
      "Fabric: 100% Organic Cotton · Hood: Lined · Pockets: Kangaroo · Machine wash warm · Made in Algeria",
    inStock: true,
    rating: 4.5,
    reviewCount: 67,
    ref: "LZL-0045",
  },
  {
    id: "6",
    name: "Urban Track Jacket",
    slug: "urban-track-jacket",
    category: "streetwear",
    price: 3290,
    images: [
      "/products/Gemini_Generated_Image_ta4kahta4kahta4k.png",
      "/products/Gemini_Generated_Image_x66q0vx66q0vx66q.png",
      "/products/Gemini_Generated_Image_omcyhvomcyhvomcy.png",
      "/products/Gemini_Generated_Image_3q6hc63q6hc63q6h.png",
    ],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Olive", hex: "#556b2f" },
    ],
    sizes: ["S", "M", "L", "XL"],
    badge: "new",
    description:
      "A modern take on the classic track jacket with premium finishes.",
    details:
      "Fabric: 90% Polyester, 10% Elastane · Closure: Full zip · Pockets: Side zip · Machine wash cold · Made in Algeria",
    inStock: true,
    rating: 4.4,
    reviewCount: 34,
    ref: "LZL-0046",
  },
  {
    id: "7",
    name: "Linen Blend Trousers",
    slug: "linen-blend-trousers",
    category: "men",
    price: 2890,
    salePrice: 3490,
    images: [
      "/products/Gemini_Generated_Image_ebfh0webfh0webfh.png",
      "/products/Gemini_Generated_Image_fp4pikfp4pikfp4p.png",
      "/products/Gemini_Generated_Image_440k5l440k5l440k.png",
      "/products/Gemini_Generated_Image_9ameg29ameg29ame.png",
    ],
    colors: [
      { name: "Beige", hex: "#d4c5a9" },
      { name: "Charcoal", hex: "#3a3a3a" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    badge: "sale",
    description: "Lightweight linen blend trousers perfect for summer.",
    details:
      "Fabric: 55% Linen, 45% Cotton · Fit: Relaxed · Closure: Button & zip · Machine wash cold · Made in Algeria",
    inStock: true,
    rating: 4.3,
    reviewCount: 78,
    ref: "LZL-0047",
  },
  {
    id: "8",
    name: "Embroidered Abaya",
    slug: "embroidered-abaya",
    category: "women",
    price: 4990,
    images: [
      "/products/Gemini_Generated_Image_agy78sagy78sagy7.png",
      "/products/Gemini_Generated_Image_omcyhvomcyhvomcy.png",
      "/products/Gemini_Generated_Image_ta4kahta4kahta4k.png",
      "/products/Gemini_Generated_Image_x66q0vx66q0vx66q.png",
    ],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Navy", hex: "#1a2744" },
      { name: "Burgundy", hex: "#722f37" },
    ],
    sizes: ["S", "M", "L", "XL"],
    badge: "bestseller",
    description:
      "An elegant embroidered abaya with delicate gold thread detailing.",
    details:
      "Fabric: 100% Premium Crepe · Embroidery: Gold thread · Length: Full · Closure: Front buttons · Dry clean only · Made in Algeria",
    inStock: true,
    rating: 4.9,
    reviewCount: 156,
    ref: "LZL-0048",
  },
  {
    id: "9",
    name: "Oversized Graphic Tee",
    slug: "oversized-graphic-tee",
    category: "streetwear",
    price: 1490,
    images: [
      "/products/Gemini_Generated_Image_8yapny8yapny8yap.png",
      "/products/Gemini_Generated_Image_4xiapv4xiapv4xia.png",
      "/products/Gemini_Generated_Image_3q6hc63q6hc63q6h.png",
      "/products/Gemini_Generated_Image_fp4pikfp4pikfp4p.png",
    ],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "White", hex: "#ffffff" },
      { name: "Sand", hex: "#c8b89a" },
    ],
    sizes: ["S", "M", "L", "XL"],
    description: "Oversized graphic tee with LAZULI branding.",
    details:
      "Fabric: 100% Heavyweight Cotton · Fit: Oversized · Print: Screen print · Machine wash cold · Made in Algeria",
    inStock: true,
    rating: 4.2,
    reviewCount: 45,
    ref: "LZL-0049",
  },
];

export const mockCategories: Category[] = [
  { id: "1", name: "Women's", slug: "women", image: "/products/Gemini_Generated_Image_3q6hc63q6hc63q6h.png", productCount: 42 },
  { id: "2", name: "Men's", slug: "men", image: "/products/Gemini_Generated_Image_440k5l440k5l440k.png", productCount: 38 },
  { id: "3", name: "Kids", slug: "kids", image: "/products/Gemini_Generated_Image_4xiapv4xiapv4xia.png", productCount: 24 },
  { id: "4", name: "Streetwear", slug: "streetwear", image: "/products/Gemini_Generated_Image_8yapny8yapny8yap.png", productCount: 18 },
  { id: "5", name: "Accessories", slug: "accessories", image: "/products/Gemini_Generated_Image_9ameg29ameg29ame.png", productCount: 31 },
];

export const SHIPPING_OPTIONS = [
  { id: "standard" as const, name: "Standard Delivery", description: "3–5 business days", price: 0, estimatedDays: "3-5 days" },
  { id: "express" as const, name: "Express Delivery", description: "1–2 business days", price: 500, estimatedDays: "1-2 days" },
  { id: "sameday" as const, name: "Same Day — Algiers Only", description: "Order before 12 PM", price: 1000, estimatedDays: "Same day" },
];
